apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
      tier: backend
  template:
    metadata:
      labels:
        app: caddy
        tier: backend
    spec:
      volumes:
      - name: dir
        persistentVolumeClaim:
          claimName: dir
      - name: config
        configMap:
          name: caddy-config
          items:
          - key: config
            path: Caddyfile
      containers:
      - name: caddy
        image: caddy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /dir
        - name: config
          mountPath: /etc/caddy
