apiVersion: v1
kind: Service
metadata:
  labels:
    tier: backend
  annotations:
    load-balancer.hetzner.cloud/location: nbg1 # must ensure the network location of the load balancer is same as for the nodes
    load-balancer.hetzner.cloud/use-private-ip: "true" # ensures the traffic between LB and nodes
  name: caddy
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php
    tier: backend
  type: LoadBalancer
