namePrefix: kustomize-

resources:
- dir_volume.yaml
- kustomization.yaml
- nginx_LoadBalancer.yaml
- nginx_configMap.yaml
- nginx_deployment.yaml
- php_deployment.yaml
- php_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
