resources:
- dir_volume.yaml
#- nginx_LoadBalancer.yaml
#- nginx_configMap.yaml
#- nginx_deployment.yaml
- php_deployment.yaml
- php_service.yaml
- caddy_LoadBalancer.yaml
- caddy_configMap.yaml
- caddy_deployment.yaml
