apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        persistentVolumeClaim:
          claimName: dir
      - name: config
        configMap:
          name: caddy-config
          items:
          - key: config
            path: Caddyfile
      containers:
      - name: php
        image: php:8.2-fpm
        volumeMounts:
        - name: dir
          mountPath: /dir
      - name: caddy
        image: caddy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /dir
        - name: config
          mountPath: /etc/caddy
      initContainers:
      - name: install
        image: ghcr.io/dergeberl/multitool:latest
        volumeMounts:
        - name: dir
          mountPath: /dir
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -O /tmp/deploy.sh https://raw.githubusercontent.com/Wunder-TV/example-php-k8s/main/deploy.sh &&
          chmod +x /tmp/deploy.sh &&
          sh /tmp/deploy.sh
