apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        persistentVolumeClaim:
          claimName: dir
      containers:
      - name: php
        image: php:8.2-fpm
        volumeMounts:
        - name: dir
          mountPath: /dir
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /dir
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -O /dir/deploy.sh https://raw.githubusercontent.com/Wunder-TV/example-php-k8s/main/deploy.sh &&
          chmod +x /dir/deploy.sh &&
          sh /dir/deploy.sh
